### PR TITLE
Rfc authentication

### LINKED ISSUE #1301: Add authentication token to RfC mails
As a _learner_,
I want to _view a Request for Comment (RfC) even when not logged in_
in order to _read replies from my fellow learners and do not get an error message_.

<hr>

Implementation Details:

- Generate user- and RfC-specific authorisation tokens
- Persist tokens and limit their validity to one week
- Send emails with the proper authentication token included
- Allow users to open the RfC with a single click as long as the token is still valid
- Preferably, the token should work for both, so-called internal and external users. If that doesn't work, external users are more important to enable the feature.

### PR DESCRIPTION
**Pull request by Janis4411**
Regarding issue: Add authentication token to RfC mails #1301

Via token authentication it is now possible to view a Request for Comment even when not logged in.

Closes #1301

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -44,6 +49,10 @@ def set_sentry_context
   end
   private :set_sentry_context
 
+  def render_authentication_error
+    render_error t('')
```
Comment (Dome-GER) [inline app/controllers/application_controller.rb:53]: Something is missing here.

File: app/controllers/request_for_comments_controller.rb [hunk 2]
```diff
@@ -144,6 +144,10 @@ def set_request_for_comment
     @request_for_comment = RequestForComment.find(params[:id])
   end
 
+  def add_authentication_token_to_params
```
Comment (Dome-GER) [inline app/controllers/request_for_comments_controller.rb:147]: I don't belong here.

File: app/models/authentication_token.rb [hunk 3]
```diff
@@ -0,0 +1,14 @@
+require 'securerandom'
+
+class AuthenticationToken < ApplicationRecord
+
+include Creation
```
Comment (Dome-GER) [inline app/models/authentication_token.rb:5]: Indentation!

File: spec/mailers/user_mailer_spec.rb [hunk 4]
```diff
@@ -60,4 +60,46 @@
       expect(mail.body).to include(reset_password_internal_user_url(user, token: user.reset_password_token))
     end
   end
+
+  describe '#got_new_comment' do
+
```
Comment (Dome-GER) [inline spec/mailers/user_mailer_spec.rb:65]: Remove this additional empty line, please.

**Review by Dome-GER — CHANGES_REQUESTED** [review]
Ignored the schema. Some minor suggestions.

File: app/controllers/application_controller.rb [hunk 5]
```diff
@@ -32,6 +32,11 @@ def mnemosyne_trace
     end
   end
 
+  def login_from_authentication_token
+    token = AuthenticationToken.find_by(shared_secret: params[:token])
+    auto_login(token.user) if token&.user && token&.expire_at&.future?
```
Comment (Dome-GER) [inline app/controllers/application_controller.rb:37]: The scenario with and expired is not tested, is it?

**Review by MrSerth — CHANGES_REQUESTED** [review]
Nice feature and very generell implementation approach, this will be well-used by future authentication features as well. 

@Janis4411 thanks for taking the time, I am convinced our learners will appreciate this new feature and like it very much! 🔥

File: spec/mailers/user_mailer_spec.rb [hunk 6]
```diff
@@ -60,4 +60,122 @@
...
+    it 'includes the correct URL' do
+      expect(mail.body).to include(request_for_comment_url(request_for_comment))
+    end
+
+    it 'includes the correct authentication token' do
+      expect(mail.body).to include(token.shared_secret)
+    end
+
+    it 'sets a new authentication token' do
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:91]:
```suggestion
    it 'creates a new authentication token' do
```

File: spec/mailers/user_mailer_spec.rb [hunk 7]
```diff
@@ -60,4 +60,122 @@
...
+      expect { mail }.to change(AuthenticationToken, :count).by(1)
+    end
+
+    it 'sets a non expired authentication token' do
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:95]:
```suggestion
    it 'sets a non-expired authentication token' do
```

File: spec/mailers/user_mailer_spec.rb [hunk 8]
```diff
@@ -60,4 +60,122 @@
...
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:135]:
```suggestion
    it 'sets a non-expired authentication token' do
```

File: spec/mailers/user_mailer_spec.rb [hunk 9]
```diff
@@ -60,4 +60,122 @@
...
+
+    it 'includes the correct URL' do
+      expect(mail.body).to include(request_for_comment_url(subscription.request_for_comment))
+    end
+
+    it 'includes the correct authentication token' do
+      expect(mail.body).to include(token.shared_secret)
+    end
+
+    it 'sets a new authentication token' do
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:131]:
```suggestion
    it 'creates a new authentication token' do
```

**Review by MrSerth — CHANGES_REQUESTED** [review]
We should add another (request) spec to check that the token could be used to sign in iff it is not expired.

File: spec/factories/authentication_token.rb [hunk 10]
```diff
@@ -0,0 +1,15 @@
...
+  factory :valid_authentication_token, class: 'AuthenticationToken' do
+    created_by_external_user
+    shared_secret { SecureRandom.hex(32) }
+    expire_at { 7.days.from_now }
+  end
+
+  factory :invalid_authentication_token, class: 'AuthenticationToken' do
+    created_by_external_user
+    shared_secret { SecureRandom.hex(32) }
+    expire_at { 8.days.ago }
```
Comment (Dome-GER) [inline spec/factories/authentication_token.rb:13]: As we are modifying this attribute only, I would have expected it to be a `authentication_token` factory with and `:invalid` trait.

**Review by MrSerth — APPROVED** [review]
Looks great, thanks for taking so much time to test the behaviour and include the small improvements along the way 👏

File: spec/features/authentication_spec.rb [hunk 11]
```diff
@@ -32,6 +32,46 @@
         expect(page).to have_content(I18n.t('sessions.create.failure'))
       end
     end
+
+    context 'with no authentication token' do
+      let(:request_for_comment) { create(:rfc_with_comment, user: user) }
+
+      it 'denies access to the request for comment' do
+        visit(request_for_comment_path(request_for_comment))
+        expect(page).to have_content(I18n.t('application.not_authorized'))
```
Comment (Dome-GER) [inline spec/features/authentication_spec.rb:41]: This very much replicates implementation. We should check for expected content.
Similar below.

File: spec/features/authentication_spec.rb [hunk 12]
```diff
@@ -32,6 +32,46 @@
...
+        let(:token) { create(:valid_authentication_token) }
+
+        it 'allows access to the request for comment' do
+          mail.deliver_now
+          visit(rfc_link)
+          expect(page).to have_content(request_for_comment.exercise.title)
+        end
+      end
+
+      context 'with a expired authentication token' do
```
Comment (Dome-GER) [inline spec/features/authentication_spec.rb:64]:
```suggestion
      context 'with an expired authentication token' do
```

:nerd

File: spec/mailers/user_mailer_spec.rb [hunk 13]
```diff
@@ -60,4 +60,122 @@
...
+    it 'sets the correct subject' do
+      expect(mail.subject).to eq(I18n.t('mailers.user_mailer.got_new_comment.subject', commenting_user_displayname: commenting_user.displayname))
+    end
+
+    it 'sets the correct receiver' do
+      expect(mail.to).to include(request_for_comment.user.email)
+    end
+
+    it 'includes the correct URL' do
+      expect(mail.body).to include(request_for_comment_url(request_for_comment))
```
Comment (Dome-GER) [inline spec/mailers/user_mailer_spec.rb:84]: What URL is expected here? Same argument as above. The authentication token is supposed to be part of this URL, isn't it? Currently, it could appear anywhere in the e-mail body. A regular expression can help here.

File: spec/mailers/user_mailer_spec.rb [hunk 14]
```diff
@@ -60,4 +60,122 @@
...
+
+    it 'includes the correct authentication token' do
+      expect(mail.body).to include(token.shared_secret)
+    end
+
+    it 'creates a new authentication token' do
+      expect { mail }.to change(AuthenticationToken, :count).by(1)
+    end
+
+    it 'sets a non-expired authentication token' do
```
Comment (Dome-GER) [inline spec/mailers/user_mailer_spec.rb:95]: What is this supposed to be testing? Especially the second part (lines 98-99) looks suspicious to me.

File: spec/mailers/user_mailer_spec.rb [hunk 15]
```diff
@@ -60,4 +60,122 @@
...
+  describe '#got_new_comment_for_subscription' do
+    let(:user) { create(:learner) }
+    let(:token) { AuthenticationToken.find_by(user: user) }
+    let(:request_for_comment) { create(:rfc_with_comment, user: user) }
+    let(:subscription) { Subscription.create(request_for_comment: request_for_comment, user: user) }
+    let(:from_user) { InternalUser.create(attributes_for(:teacher)) }
+    let(:mail) { described_class.got_new_comment_for_subscription(request_for_comment.comments.first, subscription, from_user).deliver_now }
+
+    it 'sets the correct sender' do
+      expect(mail.from).to include(CodeOcean::Application.config.action_mailer[:default_options][:from])
```
Comment (Dome-GER) [inline spec/mailers/user_mailer_spec.rb:112]: Let's use the actual value here?

**Review by Dome-GER — CHANGES_REQUESTED** [review]
Almost there 😉

File: app/controllers/application_controller.rb (hunk 5 above)
Comment (Dome-GER) [reply app/controllers/application_controller.rb]: Fine for me. As commented on the changes, the scenarios testing the `future?` look a bit suscpicious.
Other than that, I'm very happy with the result.

Comment (MrSerth) [reply app/controllers/application_controller.rb]: That's true, we also discussed the tests with the `future?` earlier today. As a consequence, the feature spec were added to test the actual behaviour for expired tokens.

File: spec/features/authentication_spec.rb [hunk 16]
```diff
@@ -32,6 +32,47 @@
...
+
+      before { allow(AuthenticationToken).to receive(:generate!).with(user).and_return(token).once }
+
+      context 'when the token is valid' do
+        let(:token) { create(:authentication_token, user: user) }
+
+        it 'allows access to the request for comment' do
+          mail.deliver_now
+          visit(rfc_link)
+          expect(page).to have_content(request_for_comment.exercise.title)
```
Comment (MrSerth) [inline spec/features/authentication_spec.rb:60]: We could check here for the URL as well:
```
expect(current_url).to be(rfc_link)
```

File: spec/features/authentication_spec.rb [hunk 17]
```diff
@@ -32,6 +32,47 @@
         expect(page).to have_content(I18n.t('sessions.create.failure'))
       end
     end
+
+    context 'with no authentication token' do
+      let(:request_for_comment) { create(:rfc_with_comment, user: user) }
+
+      it 'denies access to the request for comment' do
+        visit(request_for_comment_path(request_for_comment))
+        expect(page).to have_content(I18n.t('application.not_authorized'))
```
Comment (MrSerth) [inline spec/features/authentication_spec.rb:41]: We could check here for the URLand the RfC title as well:
```
expect(current_url).not_to be(rfc_link)
expect(page).not_to have_content(request_for_comment.exercise.title)
```

File: spec/mailers/user_mailer_spec.rb [hunk 18]
```diff
@@ -60,4 +60,107 @@
...
+
+  describe '#send_thank_you_note' do
+    let(:user) { create(:learner) }
+    let(:token) { AuthenticationToken.find_by(user: user) }
+    let(:request_for_comments) { create(:rfc_with_comment, user: user) }
+    let(:receiver) { InternalUser.create(attributes_for(:teacher)) }
+    let(:mail) { described_class.send_thank_you_note(request_for_comments, receiver).deliver_now }
+
+    it 'sets the correct sender' do
+      expect(mail.from).to include(CodeOcean::Application.config.action_mailer[:default_options][:from])
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:141]:
```suggestion
      expect(mail.from).to include('codeocean@hpi.de')
```

File: spec/mailers/user_mailer_spec.rb [hunk 19]
```diff
@@ -60,4 +60,107 @@
...
+      expect(mail.body).to include(request_for_comment_url(request_for_comments, token: token.shared_secret))
+    end
+
+    it 'creates a new authentication token' do
+      expect { mail }.to change(AuthenticationToken, :count).by(1)
+    end
+
+    it 'sets a non-expired authentication token' do
+      mail
+      # 5 minutes tolerance are allowed as the mail and the token are not created instantly at the same time.
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:162]:
```suggestion
      # A five minute tolerance is allowed to account for the time difference between `now` and the creation timestamp of the token.
```

File: spec/mailers/user_mailer_spec.rb [hunk 20]
```diff
@@ -60,4 +60,107 @@
...
+      expect(mail.body).to include(request_for_comment_url(subscription.request_for_comment, token: token.shared_secret))
+    end
+
+    it 'creates a new authentication token' do
+      expect { mail }.to change(AuthenticationToken, :count).by(1)
+    end
+
+    it 'sets a non-expired authentication token' do
+      mail
+      # 5 minutes tolerance are allowed as the mail and the token are not created instantly at the same time.
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:128]:
```suggestion
      # A five minute tolerance is allowed to account for the time difference between `now` and the creation timestamp of the token.
```

File: spec/mailers/user_mailer_spec.rb [hunk 21]
```diff
@@ -60,4 +60,107 @@
...
+      expect(mail.body).to include(request_for_comment_url(request_for_comment, token: token.shared_secret))
+    end
+
+    it 'creates a new authentication token' do
+      expect { mail }.to change(AuthenticationToken, :count).by(1)
+    end
+
+    it 'sets a non-expired authentication token' do
+      mail
+      # 5 minutes tolerance are allowed as the mail and the token are not created instantly at the same time.
```
Comment (MrSerth) [inline spec/mailers/user_mailer_spec.rb:93]:
```suggestion
      # A five minute tolerance is allowed to account for the time difference between `now` and the creation timestamp of the token.
```

**Review by MrSerth — COMMENTED** [review]
We could further simplify the specs by using `shared_example` and `include_example` (something I consider to be optional here)

File: spec/features/authentication_spec.rb (hunk 11 above)
Comment (MrSerth) [reply spec/features/authentication_spec.rb:41]: Okay, I got it (using I18n vs a string representation). Besides considering your comment for a refactoring of all specs, I would vote to leave it this way for now (to ensure all occurrences are consistent).

File: spec/features/authentication_spec.rb [hunk 22]
```diff
@@ -32,6 +32,47 @@
...
+      end
+
+      context 'with an expired authentication token' do
+        let(:token) { create(:authentication_token, :invalid, user: user) }
+
+        it 'denies access to the request for comment' do
+          mail.deliver_now
+          visit(rfc_link)
+          expect(page).not_to have_content(request_for_comment.exercise.title)
+          expect(current_url).not_to be(rfc_link)
```
Comment (MrSerth) [inline spec/features/authentication_spec.rb:71]:
```suggestion
          expect(response).to redirect_to(root_path)
```

File: spec/features/authentication_spec.rb (hunk 16 above)
Comment (Dome-GER) [reply spec/features/authentication_spec.rb:60]: That's rather a case for 

```suggestion
          expect(response).to have_http_status :ok
          expect(page).to have_content(request_for_comment.exercise.title)
```

File: spec/features/authentication_spec.rb (hunk 17 above)
Comment (MrSerth) [reply spec/features/authentication_spec.rb:45]: Using a `response` in feature specs is neither supported nor recommended (as this should be done in a request spec). Therefore, we could not implement the spec as suggested here, but rather sticked with the existing method to verify the URL and the exercise title.

File: spec/features/authentication_spec.rb (hunk 16 above)
Comment (MrSerth) [reply spec/features/authentication_spec.rb:65]: As mentioned above, using a response in feature specs is neither supported nor recommended (as this should be done in a request spec). Therefore, we could not implement the spec as suggested here, but rather sticked with the existing method to verify the URL and the exercise title.

File: spec/mailers/user_mailer_spec.rb (hunk 14 above)
Comment (MrSerth) [reply spec/mailers/user_mailer_spec.rb:91]: We removed the two suspicious lines and improved the spec. It now checks that a token valid for seven days is created for authentication.

**Review by MrSerth — APPROVED** [review]

**Review by Dome-GER — APPROVED** [review]
Nice result, I like it! 👍
